# Generated by Django 4.2.7 on 2024-01-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_products_currency_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
