services:
  - type: web
    name: focus-garden
    env: node
    buildCommand: |
      npm install && npm run build
    startCommand: cd backend && npm install && npm start
    envVars:
      - key: NODE_ENV
        value: production
